name: expenseo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  auto_size_text: ^3.0.0
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.3
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.1
  font_awesome_flutter: ^11.0.0
  gap: ^3.0.1
  get_it: ^9.2.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.0.0
  home_widget: ^0.9.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  pinput: ^5.0.1
  quick_actions: ^1.0.8
  shared_preferences: ^2.5.5
  skeletonizer: ^2.1.3
  uuid: ^4.5.3
  # Security Dependencies
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  pin_plus_keyboard: ^3.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  leancode_lint: ^19.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/expenseo.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/expenseo.png
    icon_background_color: "#FFFFFF"
