// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq4uHdl1nuYlr3Hc5k876JFmj5AvZNg6E',
    appId: '1:447111972966:web:2d8931c7a71b12e8ae85a7',
    messagingSenderId: '447111972966',
    projectId: 'expenseo-39754',
    authDomain: 'expenseo-39754.firebaseapp.com',
    storageBucket: 'expenseo-39754.firebasestorage.app',
    measurementId: 'G-1EY2LL6KDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu09KgDWdEOJLmbTOfhfnSYnmONASTyfc',
    appId: '1:447111972966:android:3ea4638115513a26ae85a7',
    messagingSenderId: '447111972966',
    projectId: 'expenseo-39754',
    storageBucket: 'expenseo-39754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNypILGQBeb_wIjheBKhadNgNSa-mVvlc',
    appId: '1:447111972966:ios:84b3cacb4cae5d05ae85a7',
    messagingSenderId: '447111972966',
    projectId: 'expenseo-39754',
    storageBucket: 'expenseo-39754.firebasestorage.app',
    iosBundleId: 'com.example.expenseo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNypILGQBeb_wIjheBKhadNgNSa-mVvlc',
    appId: '1:447111972966:ios:84b3cacb4cae5d05ae85a7',
    messagingSenderId: '447111972966',
    projectId: 'expenseo-39754',
    storageBucket: 'expenseo-39754.firebasestorage.app',
    iosBundleId: 'com.example.expenseo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq4uHdl1nuYlr3Hc5k876JFmj5AvZNg6E',
    appId: '1:447111972966:web:0d1b2e72ec6c8aabae85a7',
    messagingSenderId: '447111972966',
    projectId: 'expenseo-39754',
    authDomain: 'expenseo-39754.firebaseapp.com',
    storageBucket: 'expenseo-39754.firebasestorage.app',
    measurementId: 'G-QLMVT77M0S',
  );
}
